version: "3.9"
services:
  postgres:
    container_name: postgres_unleash_demo
    image: "postgres:13.2"
    volumes:
      - /private/var/docker_volumes/postgre_db:/var/lib/postgresql/data/
      - ./keycloak_startup:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./db_dev.env
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin_unleash_demo
    image: "dpage/pgadmin4:5.1"
    env_file:
      - ./db_dev.env
    ports:
      - "5050:80"
    networks:
      - backend
  keycloak:
    container_name: keycloak_unleash_demo
    image: "alemairebe/keycloak:14.0.0"
    env_file:
      - ./keycloak_dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge